export const CHANNEL = {
  LOGIN: 'LOGIN',
  SCRAP: 'SCRAP',
  OPEN_SCREENSHOT_DIRECTORY: 'OPEN_SCREENSHOT_DIRECTORY',
  OPEN_FILE: 'OPEN_FILE',
  OPEN_URL: 'OPEN_URL',
  SHOW_ERROR_DIALOG: 'SHOW_ERROR_DIALOG',
} as const;
